apiVersion: v1
kind: Service
metadata:
  name: jenkins-cicd-test-service
spec:
  type: LoadBalancer
  selector:
    app: jenkins-cicd-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080